language: java
sudo: false

jdk:
  - openjdk8
  - openjdk11
  - openjdk-ea
  
matrix:
  allow_failures:
    - jdk: openjdk11
    - jdk: openjdk-ea

script: "mvn cobertura:cobertura"

after_success:
- bash <(curl -s https://codecov.io/bash)
